version: 2.1
jobs:
  build:
    docker: 
      - image: debian/testing-slim
    steps:
      - run: cat /proc/cpuinfo
      - run: sudo add-apt-repository 'ppa:ubuntu-toolchain-r/test' && sudo apt-get update && sudo apt-get install -y ninja-build ninja-build python3-pip python3-setuptools python3-wheel parallel gcovr libsleef-dev
      - run: pip3 install meson
      - run: ~/.local/bin/meson setup build -Db_coverage=true
      - run: ninja -C build -v
      - run: ninja -C build -v test
